- name: add spotify repo key
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: BBEBDCB318AD50EC6865090613B00F1FD2C19886

- name: add spotify repo
  become: yes
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present

- name: install spotify
  become: yes
  apt:
    name: spotify-client
    state: present
    update_cache: yes
