- name: copy install script
  become: yes
  copy:
    src: install.sh
    dest: /tmp/install.sh
    mode: 0755

- name: install build prerequisites
  become: yes
  apt:
    name: emacs
    state: build-dep
    update_cache: yes
  register: apt_res
  retries: 5
  until: apt_res is success

- name: build deps
  become: yes
  apt:
    name:
      - libgccjit0
      - libgccjit-10-dev
      - libjansson4
      - libjansson-dev
      - gnutls-bin
      - libtree-sitter-dev
      - gcc-10
      - imagemagick
      - libmagick++-dev
      - libwebp-dev
      - webp
      - libxft-dev
      - libxft2

- name: install version 29.3
  become: yes
  command: /tmp/install.sh
  args:
    creates: /usr/local/bin/emacs

- name: install doom emacs
  git:
    repo: https://github.com/doomemacs/doomemacs
    dest: ~/.config/emacs
    update: no
