tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "px4/px4"
tap "d12frosted/emacs-plus"

brew "mas"
brew "ack"
brew "ansible"
brew "asdf"
brew "autoconf"
brew "avrdude"
brew "awscli"
brew "coreutils"
brew "cowsay"
brew "curl"
brew "dfu-programmer"
brew "dfu-util"
brew "docker-machine-driver-hyperkit"
brew "fontconfig"
brew "fortune"
brew "git"
brew "htop"
brew "hyperkit"
brew "jq"
brew "libtool"
brew "libxslt"
brew "libyaml"
brew "markdown"
brew "openssl"
brew "ponysay"
brew "pipenv"
brew "readline"
brew "the_silver_searcher"
brew "tmux"
brew "unixodbc"
brew "unzip"
brew "vim"
brew "adr-tools"
brew "autojump"
brew "zsh"
brew "emacs-plus"
brew "ripgrep"
brew "fd"


cask "alacritty"
cask "docker"
cask "evernote"
cask "firefox-developer-edition"
cask "font-hack-nerd-font"
cask "font-open-sans"
cask "google-chrome"
cask "gimp"
cask "slack"
cask "spotify"
cask "bitwarden"
cask "alfred"
cask "postman"
cask "notion"
cask "microsoft-teams"
cask "rectangle"

mas Fantastical, id: 975937182
mas Everynote Web Clipper, id: 1481669779
