- hosts: all
  roles:
    - base
    - shell
    - dotfiles
    - editors
#    - desktop
#    - virtualbox
#    - vagrant
    - chrome
    - slack
#    - graphics
#    - openjdk
#    - leiningen
#    - music
#    - nodejs
#    - keybase
#    - python
#    - video
#    - herokucli
#    - audio
#    - docker
#    - terraform
#    - aws
#    - resilio-sync
    - tmux
#    - wine
#    - { role: gantsign.golang, golang_path: '$HOME/src/go' }
