- include: startup_apps.yml

- name: install sysctl.conf
  become: yes
  copy:
    src: etc/sysctl.conf
    dest: /etc/sysctl.conf

- name: update sysctl
  become: yes
  shell: sysctl -p /etc/sysctl.conf

- name: add sound-switcher-indicator repo
  become: yes
  apt_repository:
    repo: 'ppa:yktooo/ppa'
    state: present

- name: install sound-switcher-indicator
  become: yes
  apt:
    name: indicator-sound-switcher
    update_cache: yes

- name: add netspeed indicator repo
  become: yes
  apt_repository:
    repo: 'ppa:fixnix/netspeed'
    state: present

- name: install netspeed indicator
  become: yes
  apt:
    name: indicator-netspeed-unity
    update_cache: yes

- name: add caffiene indicator repo
  become: yes
  apt_repository:
    repo: 'ppa:caffeine-developers/ppa'
    state: present

- name: install caffiene indicator
  become: yes
  apt:
    name: caffeine
    update_cache: yes

- name: install load indicator
  become: yes
  apt:
    name: indicator-multiload
    update_cache: yes
