- name: download package
  get_url:
    url: 'https://github.com/tinytacoteam/zazu/releases/download/v0.3.2/zazu-v0.3.2-linux-x64.deb'
    dest: /tmp/zazu.deb
    timeout: 1200

- name: install zazu
  become: yes
  apt:
    deb: /tmp/zazu.deb
