- stat:
    path: /usr/bin/vagrant
  register: vagrant

- name: download package
  get_url:
    url: https://releases.hashicorp.com/vagrant/1.9.3/vagrant_1.9.3_x86_64.deb
    dest: /tmp/vagrant_1.9.3_x86_64.deb
  when: vagrant.stat.exists == False

- name: install
  become: yes
  apt:
    deb: /tmp/vagrant_1.9.3_x86_64.deb
  when: vagrant.stat.exists == False
