- name: install asdf
  ansible.builtin.unarchive:
    src: "https://github.com/asdf-vm/asdf/releases/download/{{ asdf_version }}/asdf-{{ asdf_version }}-linux-amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: true
    mode: '755'
  become: true
