- name: add repo
  become: yes
  apt_repository:
    repo: 'deb http://repository.spotify.com stable non-free'
    state: present

- name: add key
  become: yes
  apt_key:
    state: present
    keyserver: keyserver.ubuntu.com
    id: BBEBDCB318AD50EC6865090613B00F1FD2C19886 

- name: install spotify
  become: yes
  apt:
    name: spotify-client
    state: installed
    update_cache: yes
