- name: download package
  get_url:
    url: https://downloads.slack-edge.com/desktop-releases/linux/x64/4.43.51/slack-desktop-4.43.51-amd64.deb
    dest: /tmp/slack-desktop-4.43.51-amd64.deb

- name: install
  become: yes
  apt:
    deb: /tmp/slack-desktop-4.43.51-amd64.deb
