- name: copy install script
  become: yes
  copy:
    src: install.sh
    dest: /tmp/install.sh
    mode: 0755

- name: install build prerequisites
  become: true
  apt:
    name: emacs24
    state: build-dep
    update_cache: yes

- name: install version 25.1
  become: yes
  command: /tmp/install.sh
  args:
    creates: /usr/local/bin/emacs

- name: install spacemacs
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: ~/.emacs.d

- name: get the current user
  local_action: command whoami
  register: current_user

- name: install emacs service
  become: yes
  template:
    src: emacs.service.j2
    dest: /etc/systemd/system/emacs.service

- name: reload daemon
  become: yes
  command: systemctl daemon-reload

- name: start emacs service
  become: yes
  service:
    name: emacs.service
    enabled: yes
    state: started
