- name: add repo
  become: yes
  apt_repository:
    repo: 'deb http://download.virtualbox.org/virtualbox/debian xenial contrib'
    state: present

- name: add key
  become: yes
  apt_key:
    url: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'
    state: present

- name: install virtualbox 5.1
  become: yes
  apt:
    name: virtualbox-5.1
    state: installed
    update_cache: yes
