- name: copy install script
  become: yes
  copy:
    src: install.sh
    dest: /tmp/install.sh
    mode: 0755

- name: install build prerequisites
  become: true
  apt:
    name: tmux
    state: build-dep

- name: install tmux
  become: yes
  command: /tmp/install.sh
  args:
    creates: /usr/local/bin/tmux
