- name: install base packages
  apt:
    name:
      - autojump
      - bash-completion
      - vim
      - git
      - git-core
      - git-email
      - git-extras
      - curl
      - jq
      - wget
      - htop
      - ack-grep
      - silversearcher-ag
      - unzip
      - tar
      - gzip
      - bzip2
      - build-essential
      - gcc
      - g++
      - gnome-tweaks
      - xsel
    state: present
  become: true

- name: remap keys
  become: true
  copy:
    src: keyboard
    dest: /etc/default/keyboard

- name: get nerd fonts
  ansible.builtin.git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    clone: yes
    depth: 1
    dest: ~/src/nerd-fonts
    version: v3.3.0

- name: add open-razer repo
  ansible.builtin.apt_repository:
    repo: 'ppa:openrazer/stable'
    update_cache: true
  become: true

- name: install open-razer meta
  ansible.builtin.apt:
    name: openrazer-meta
    state: present
  become: true

- name: add polychromatic repo
  ansible.builtin.apt_repository:
    repo: 'ppa:polychromatic/stable'
    update_cache: true
  become: true

- name: install polychromatic
  ansible.builtin.apt:
    name: polychromatic
    state: present
  become: true

- name: ensure openrazer kernel mod is loaded
  ansible.builtin.command: "sudo modprobe razermouse"

- name: user in plugdev group
  ansible.builtin.user:
    name: akjones
    append: true
    groups:
      - plugdev
  become: true
