- name: install base packages
  apt:
    name:
      - bash-completion
      - vim
      - git
      - git-core
      - git-email
      - git-extras
      - curl
      - jq
      - wget
      - htop
      - ack-grep
      - silversearcher-ag
      - terminator
      - unzip
      - tar
      - gzip
      - bzip2
      - build-essential
      - gcc
      - g++
      - gnome-tweak-tool
    state: present
  become: yes

- name: remap keys
  become: yes
  copy:
    src: keyboard
    dest: /etc/default/keyboard
